INPUT:
  MAX_SEQ_LEN: 20

DATASET:
  NAME: 'referit'
  VOCAB_SIZE: 8802
  DATA_PICKLE: 'data/referit/referit_refs_pseudo.pkl'
  VOCAB_PICKLE: 'data/referit/referit_vocab.pkl'
  TRAIN: 'trainval'
  DEV: 'test'
  TEST: 'test'

OUTPUT:
  SAVE_NAME: 'referit_warmup_listener_bs_64_lr_3e-5_lrdecay_3'
  CHECKPOINT_DIR: './exp/listener'

OPTIMIZATION:
  EPOCHS: 30
  BATCH_SIZE: 64
  LISTENER_LR: 3e-5
  CLIP_MAX_NORM: 0.1
  LR_DECAY_FREQ: 3
